version: 2

models:
  - name: by_company
    columns:
      - name: company_id
        tests:
          - unique
          - not_null
  - name: by_tripmiles
    columns:
      - name: total_trip_miles
        tests:
          - unique
          - not_null
  - name: by_date
    columns:
      - name: total_trip
        tests:
          - unique
          - not_null